select * into #driver_stats_upd from driver_stats where 1=2;

LOAD into table #driver_stats_upd
(   employee_num             '|:|',
    terminal_num             '|:|',
    conv_time_date           '|:|',
    route_num                '|:|',
    emp_start_shift_time     '|:|',
    emp_left_terminal_time   '|:|',
    emp_start_del_time       '|:|',
    emp_end_del_time         '|:|',
    emp_start_lunch_time     '|:|',
    emp_end_lunch_time       '|:|',
    emp_start_pickup_time    '|:|',
    emp_end_pickup_time      '|:|',
    emp_start_break1_time    '|:|',
    emp_end_break1_time      '|:|',
    emp_start_break2_time    '|:|',
    emp_end_break2_time      '|:|',
    emp_return_terminal_time '|:|',
    emp_end_shift_time       '|:|',
    emp_regular_hours        '|:|',
    emp_overtime_hours       '|:|',
    eod_cod_cash             '|:|',
    eod_cod_cheque           '|:|',
    eod_cod_dts              '|:|',
    eod_cod_total_labels     '|:|',
    num_delivery_stops       '|:|',
    num_delivery_recs        '|:|',
    num_delivered_packages   '|:|',
    num_delivered_cod        '|:|',
    num_pickup_recs          '|:|',
    num_missed_pickups       '|:|',
    num_send_again           '|:|',
    num_cod_no_money         '|:|',
    num_refused              '|:|',
    num_return_to_sender     '|:|',
    num_not_home             '|:|',
    num_pickup_tags          '|:|',
    num_cancel_cod           '|:|',
    num_hold_for_pickup      '|:|',
    num_cannot_locate        '|:|',
    num_split_shipment       '|:|',
    num_change_of_address    '|:|',
    num_misroute             '|:|',
    num_nonattempt           '|:|',
    num_return_cod           '|:|',
    num_no_sign_required     '|:|',
    num_pickup_stops         '|:|',
    num_pickup_packages      '|:|',
    num_pickup_cod           '|:|',
    num_pickup_select        '|:|',
    num_pickup_hvr           '|:|',
    eod_comments2            '|:|',
    emp_start_break3_time    '|:|',
    emp_end_break3_time      '|:|',
    inserted_on_cons         '|:|',
    updated_on_cons          '\n'
)
from '/opt/sybase/bcp_data/cpscan/driver_stats_upd.dat'
QUOTES OFF
ESCAPES OFF
BYTE ORDER LOW
FORMAT ascii
NOTIFY 100000
IGNORE CONSTRAINT UNIQUE 0;


update driver_stats
set     	
        t.route_num                = upd.emp_start_shift_time,
        t.emp_start_shift_time     = upd.emp_left_terminal_time,
        t.emp_left_terminal_time   = upd.emp_start_del_time,
        t.emp_start_del_time       = upd.emp_start_del_time,
        t.emp_end_del_time         = upd.emp_end_del_time,
        t.emp_start_lunch_time     = upd.emp_start_lunch_time,
        t.emp_end_lunch_time       = upd.emp_end_lunch_time,
        t.emp_start_pickup_time    = upd.emp_start_pickup_time,
        t.emp_end_pickup_time      = upd.emp_end_pickup_time,
        t.emp_start_break1_time    = upd.emp_start_break1_time,
        t.emp_end_break1_time      = upd.emp_end_break1_time,
        t.emp_start_break2_time    = upd.emp_start_break2_time,
        t.emp_end_break2_time      = upd.emp_end_break2_time,
        t.emp_return_terminal_time = upd.emp_return_terminal_time,
        t.emp_end_shift_time       = upd.emp_end_shift_time,
        t.emp_regular_hours        = upd.emp_regular_hours,
        t.emp_overtime_hours       = upd.emp_overtime_hours,
        t.eod_cod_cash             = upd.eod_cod_cash,
        t.eod_cod_cheque           = upd.eod_cod_cheque,
        t.eod_cod_dts              = upd.eod_cod_dts,
        t.eod_cod_total_labels     = upd.eod_cod_total_labels,
        t.num_delivery_stops       = upd.num_delivery_stops,
        t.num_delivery_recs        = upd.num_delivery_recs,
        t.num_delivered_packages   = upd.num_delivered_packages,
        t.num_delivered_cod        = upd.num_delivered_cod,
        t.num_pickup_recs          = upd.num_pickup_recs,
        t.num_missed_pickups       = upd.num_missed_pickups,
        t.num_send_again           = upd.num_send_again,
        t.num_cod_no_money         = upd.num_cod_no_money,
        t.num_refused              = upd.num_refused,
        t.num_return_to_sender     = upd.num_return_to_sender,
        t.num_not_home             = upd.num_not_home,
        t.num_pickup_tags          = upd.num_pickup_tags,
        t.num_cancel_cod           = upd.num_cancel_cod,
        t.num_hold_for_pickup      = upd.num_hold_for_pickup,
        t.num_cannot_locate        = upd.num_cannot_locate,
        t.num_split_shipment       = upd.num_split_shipment,
        t.num_change_of_address    = upd.num_change_of_address,
        t.num_misroute             = upd.num_misroute,
        t.num_nonattempt           = upd.num_nonattempt,
        t.num_return_cod           = upd.num_return_cod,
        t.num_no_sign_required     = upd.num_no_sign_required,
        t.num_pickup_stops         = upd.num_pickup_stops,
        t.num_pickup_packages      = upd.num_pickup_packages,
        t.num_pickup_cod           = upd.num_pickup_cod,
        t.num_pickup_select        = upd.num_pickup_select,
        t.num_pickup_hvr           = upd.num_pickup_hvr,
        t.eod_comments2            = upd.eod_comments2,
        t.emp_start_break3_time    = upd.emp_start_break3_time,
        t.emp_end_break3_time      = upd.emp_end_break3_time,
    	t.updated_on_cons          = upd.updated_on_cons

from driver_stats t, #driver_stats_upd upd
where t.employee_num      = upd.employee_num and
      t.terminal_num      = upd.terminal_num and
      t.conv_time_date    = upd.conv_time_date;
